<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251224225737 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE commande DROP CONSTRAINT clientfk');
        $this->addSql('ALTER TABLE commande DROP CONSTRAINT menufk');
        $this->addSql('ALTER TABLE commande DROP CONSTRAINT burgerfk');
        $this->addSql('ALTER TABLE commande DROP CONSTRAINT complementfk');
        $this->addSql('ALTER TABLE menu DROP CONSTRAINT complementfk');
        $this->addSql('ALTER TABLE menu DROP CONSTRAINT burgerfk');
        $this->addSql('ALTER TABLE quartier DROP CONSTRAINT zonefk');
        $this->addSql('DROP TABLE "__EFMigrationsHistory"');
        $this->addSql('DROP TABLE burger');
        $this->addSql('DROP TABLE client');
        $this->addSql('DROP TABLE commande');
        $this->addSql('DROP TABLE complement');
        $this->addSql('DROP TABLE menu');
        $this->addSql('DROP TABLE quartier');
        $this->addSql('DROP TABLE zone');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "__EFMigrationsHistory" ("MigrationId" VARCHAR(150) NOT NULL, "ProductVersion" VARCHAR(32) NOT NULL, PRIMARY KEY ("MigrationId"))');
        $this->addSql('CREATE TABLE burger (id INT NOT NULL, name VARCHAR DEFAULT NULL, price DOUBLE PRECISION DEFAULT NULL, description TEXT DEFAULT NULL, imagepath VARCHAR DEFAULT NULL, archived BOOLEAN DEFAULT false, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX burger_name_key ON burger (name)');
        $this->addSql('CREATE TABLE client (id INT NOT NULL, firstname VARCHAR DEFAULT NULL, lastname VARCHAR DEFAULT NULL, email VARCHAR DEFAULT NULL, phone VARCHAR DEFAULT NULL, passwordhash VARCHAR DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE commande (id INT NOT NULL, clientid INT DEFAULT NULL, menuid INT DEFAULT NULL, burgerid INT DEFAULT NULL, complementid INT DEFAULT NULL, datecommande TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, statut VARCHAR DEFAULT NULL, modepaiement VARCHAR DEFAULT NULL, archived BOOLEAN DEFAULT NULL, typecons VARCHAR DEFAULT NULL, montanttotal DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6EEAA67D7F98CD1C ON commande (clientid)');
        $this->addSql('CREATE INDEX IDX_6EEAA67D23591A3E ON commande (menuid)');
        $this->addSql('CREATE INDEX IDX_6EEAA67D81294E14 ON commande (burgerid)');
        $this->addSql('CREATE INDEX IDX_6EEAA67DFE1C5160 ON commande (complementid)');
        $this->addSql('CREATE TABLE complement (id INT NOT NULL, name VARCHAR DEFAULT NULL, price DOUBLE PRECISION DEFAULT NULL, imagepath VARCHAR DEFAULT NULL, archived BOOLEAN DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX complement_name_key ON complement (name)');
        $this->addSql('CREATE TABLE menu (id INT NOT NULL, nom VARCHAR DEFAULT NULL, description VARCHAR DEFAULT NULL, burgerid INT DEFAULT NULL, complementid INT DEFAULT NULL, price DOUBLE PRECISION DEFAULT NULL, imagepath VARCHAR DEFAULT NULL, archived BOOLEAN DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7D053A93FE1C5160 ON menu (complementid)');
        $this->addSql('CREATE INDEX IDX_7D053A9381294E14 ON menu (burgerid)');
        $this->addSql('CREATE TABLE quartier (id INT NOT NULL, nom VARCHAR DEFAULT NULL, zoneid INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FEE8962D6B1C93CC ON quartier (zoneid)');
        $this->addSql('CREATE TABLE zone (id INT NOT NULL, nom VARCHAR DEFAULT NULL, prixlivraison DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE commande ADD CONSTRAINT clientfk FOREIGN KEY (clientid) REFERENCES client (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE commande ADD CONSTRAINT menufk FOREIGN KEY (menuid) REFERENCES menu (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE commande ADD CONSTRAINT burgerfk FOREIGN KEY (burgerid) REFERENCES burger (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE commande ADD CONSTRAINT complementfk FOREIGN KEY (complementid) REFERENCES complement (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE menu ADD CONSTRAINT complementfk FOREIGN KEY (complementid) REFERENCES complement (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE menu ADD CONSTRAINT burgerfk FOREIGN KEY (burgerid) REFERENCES burger (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE quartier ADD CONSTRAINT zonefk FOREIGN KEY (zoneid) REFERENCES zone (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
